apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: irrigation
type: Opaque
stringData:
  POSTGRES_ENERGIE_USER: "energie_user"
  POSTGRES_ENERGIE_PASSWORD: "energie_pass"
  POSTGRES_EAU_USER: "eau_user"
  POSTGRES_EAU_PASSWORD: "eau_pass"
