apiVersion: apps/v1
kind: Deployment
metadata:
  name: eau-service
  namespace: irrigation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eau-service
  template:
    metadata:
      labels:
        app: eau-service
    spec:
      containers:
      - name: eau-service
        image: systeme-gestion-energie-eau-pour-station-irrigation-eau-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-eau:5432/eaudb"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_EAU_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_EAU_PASSWORD
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: eureka-config
              key: EUREKA_SERVER_URL
